# Generated by Django 4.0.3 on 2022-05-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_nodeproperties_nodetypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodeproperties',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
