# Generated by Django 4.0.3 on 2022-05-06 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_linkproperties_linktypes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LinkProperties',
        ),
        migrations.RemoveField(
            model_name='linktypes',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='NodeProperties',
        ),
        migrations.RemoveField(
            model_name='nodetypes',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='LinkTypes',
        ),
        migrations.DeleteModel(
            name='NodeTypes',
        ),
    ]
