# Generated by Django 4.1.2 on 2023-07-17 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseEnroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('order', models.IntegerField(default=1)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning.courses')),
            ],
        ),
        migrations.CreateModel(
            name='LectureMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='matial name', max_length=50)),
                ('order', models.IntegerField(default=1)),
                ('materialType', models.CharField(choices=[('PDF', 'PDF'), ('IMAGE', 'IMAGE'), ('VIDEO', 'VIDEO'), ('TEMPLATE', 'TEMPLATE')], default='1', max_length=20)),
                ('materialFiles', models.FileField(upload_to='elerning_material/')),
                ('template', models.CharField(choices=[('image.html', 'image'), ('video.html', 'video'), ('header-text.html', 'header-text')], default='N/A', max_length=20)),
                ('value_1', models.TextField(default='N/A', max_length=1000)),
                ('value_2', models.TextField(default='N/A', max_length=1000)),
                ('value_3', models.TextField(default='N/A', max_length=1000)),
                ('value_4', models.TextField(default='N/A', max_length=1000)),
                ('value_5', models.TextField(default='N/A', max_length=1000)),
                ('value_6', models.TextField(default='N/A', max_length=1000)),
                ('value_7', models.TextField(default='N/A', max_length=1000)),
                ('value_8', models.TextField(default='N/A', max_length=1000)),
                ('value_9', models.TextField(default='N/A', max_length=1000)),
                ('value_10', models.TextField(default='N/A', max_length=1000)),
                ('value_11', models.TextField(default='N/A', max_length=1000)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning.courses')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning.lecture')),
            ],
        ),
        migrations.CreateModel(
            name='newspasper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=1000)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(max_length=50)),
                ('card_number', models.CharField(max_length=16)),
                ('expiration_date', models.DateField()),
                ('cvv', models.CharField(max_length=4)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('content', models.TextField()),
                ('img', models.ImageField(upload_to='elerning_subjects/')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileElearning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('one_click_purchasing', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('courses_enroll', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='elearning.courseenroll')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning.paymentmethod')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_on', models.DateTimeField(blank=True, null=True)),
                ('LectureMaterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning.lecturematerial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LectureMaterialEnroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lectureMaterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning.lecturematerial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LectureEnroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning.lecture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='relatedJobs',
            field=models.ManyToManyField(to='elearning.jobs'),
        ),
        migrations.AddField(
            model_name='courses',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning.subjects'),
        ),
        migrations.AddField(
            model_name='courseenroll',
            name='courses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning.courses'),
        ),
        migrations.AddField(
            model_name='courseenroll',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(max_length=30)),
                ('optionI', models.CharField(max_length=30)),
                ('optionII', models.CharField(max_length=30)),
                ('optionIII', models.CharField(max_length=30)),
                ('optionIIII', models.CharField(max_length=30)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning.questions')),
            ],
        ),
    ]
