# Generated by Django 4.1.2 on 2023-07-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='des',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
