# Generated by Django 4.1.2 on 2023-07-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0002_courses_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='img',
            field=models.ImageField(default='img', upload_to='elerning_course_img/'),
        ),
    ]
