# Generated by Django 4.1.2 on 2023-07-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0003_courses_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='des',
            new_name='longdes',
        ),
        migrations.AddField(
            model_name='courses',
            name='shortdes',
            field=models.TextField(default='', max_length=250),
        ),
    ]
