# Generated by Django 4.1.2 on 2023-07-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0005_courses_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='courseenroll',
            name='timedelta',
            field=models.IntegerField(default=30),
        ),
    ]
