# Generated by Django 4.1.2 on 2023-08-03 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0007_alter_courses_img_alter_subjects_img_questionstaken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='courses',
            name='feature',
            field=models.TextField(default='<div>\n    <p><i class="fa fa-alarm"></i>feature one</p>\n    <p><i class="bi bi-alarm"></i>feature two</p>\n</div>', help_text='HTML view of feature page', max_length=1000),
        ),
        migrations.AlterField(
            model_name='courses',
            name='img',
            field=models.ImageField(default='default.png', upload_to='elerning_course_img/'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='longdes',
            field=models.TextField(default='', help_text='long description is 2000 Char long max,its appear on Course view page', max_length=2000),
        ),
        migrations.AlterField(
            model_name='courses',
            name='name',
            field=models.CharField(blank=True, help_text='Add course name example:Python advance', max_length=40, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='shortdes',
            field=models.TextField(default='', help_text='Short description is 250 Char long max,its appear on top of the course card', max_length=250),
        ),
        migrations.AlterField(
            model_name='courses',
            name='subject',
            field=models.ForeignKey(help_text='Select subjects', on_delete=django.db.models.deletion.CASCADE, to='elearning.subjects'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='img',
            field=models.ImageField(default='default.png', upload_to='elerning_subjects/'),
        ),
    ]
