# Generated by Django 4.1.2 on 2023-08-03 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0008_alter_courses_amount_alter_courses_feature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionstaken',
            name='answerStatus',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='questionstaken',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elearning.questions'),
        ),
    ]
