# Generated by Django 4.1.2 on 2023-08-03 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0009_questionstaken_answerstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionstaken',
            name='answer',
            field=models.CharField(default='', max_length=50),
        ),
    ]
