# Generated by Django 4.1.2 on 2023-08-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0010_questionstaken_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='question_type',
            field=models.CharField(choices=[('multiplechoices', 'multiplechoices')], default='1', max_length=20),
        ),
    ]
