# Generated by Django 4.1.2 on 2023-08-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0011_questions_question_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeUI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navbar_fontSize', models.IntegerField(default=25)),
            ],
        ),
        migrations.AlterField(
            model_name='questions',
            name='question_type',
            field=models.CharField(choices=[('singlechoices', 'singlechoices')], default='1', max_length=20),
        ),
    ]
