# Generated by Django 4.1.2 on 2023-08-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0012_themeui_alter_questions_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='themeui',
            name='profile_counters',
            field=models.CharField(default='', max_length=50),
        ),
    ]
