# Generated by Django 4.1.2 on 2023-08-10 08:29

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0013_themeui_profile_counters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themeui',
            name='profile_counters',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=18, samples=None),
        ),
    ]
