# Generated by Django 4.1.2 on 2023-08-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0014_alter_themeui_profile_counters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_one', models.CharField(default='The Binary Tower', max_length=50)),
                ('location_two', models.CharField(default='32 Marasi Drive Street - Business Bay - Dubai', max_length=50)),
                ('contact_number', models.CharField(default='+971 56 651 0454', max_length=50)),
                ('facebook', models.CharField(default='#', max_length=50)),
                ('twitter', models.CharField(default='#', max_length=50)),
                ('instagram', models.CharField(default='#', max_length=50)),
            ],
        ),
    ]
