# Generated by Django 4.1.2 on 2023-08-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0015_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='logo',
            field=models.ImageField(default='defaultlogo.png', upload_to='elerning_course_img/'),
        ),
    ]
