# Generated by Django 4.2.4 on 2023-08-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elearning', '0016_information_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='img',
            field=models.ImageField(default='default.png', upload_to='elerning_course_img/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='longdes',
            field=models.TextField(default='', help_text='long description is 2000 Char long max,its appear on Course view page', max_length=2000, verbose_name='Long description'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='shortdes',
            field=models.TextField(default='', help_text='Short description is 250 Char long max,its appear on top of the course card', max_length=250, verbose_name='Short description'),
        ),
    ]
